/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scale.test.java;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.glassfish.jersey.moxy.json.MoxyJsonFeature;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.server.ServerProperties;
import org.glassfish.jersey.servlet.ServletContainer;

public class App {

    public static void main(String[] args) throws Exception {
        ServletContextHandler ctx = new ServletContextHandler(ServletContextHandler.SESSIONS);
        ctx.setContextPath("/");

        Server jettyServer = new Server(8080);
        jettyServer.setHandler(ctx);

        ResourceConfig rc = new ResourceConfig() {{
            packages("scale.test.java");
        }};
        rc.registerClasses(MoxyJsonFeature.class);

        ServletContainer sc = new ServletContainer(rc);

        ServletHolder sh = new ServletHolder(sc);
        sh.setInitOrder(0);
        sh.setInitParameter(
                ServerProperties.PROVIDER_CLASSNAMES,
                AccountWS.class.getCanonicalName()
        );

        ctx.addServlet(sh, "/*");

        try {
            jettyServer.start();
            jettyServer.join();
        } finally {
            jettyServer.destroy();
        }
    }
}
